# Inventory file - lists the servers Ansible will manage

# Local machine (used by simple playbook)
[local]
localhost ansible_connection=local

# Docker container (used by webserver playbook)
[docker]
target ansible_connection=docker     #container name, connect using Docker
